// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfupzofhgkrxzqzmyfil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mdXB6b2ZoZ2tyeHpxem15ZmlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDYwMzAsImV4cCI6MjA2OTkyMjAzMH0.wfwD8V-3JdTgpJsMjJ4-onGuGlC3l13COJf07Vcxq-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});